development:
   adapter: mysql2
   database: userRecognitions
   username: root
   password: NEWPASSWORD
   host: localhost

test:
   adapter: mysql2
   database: userRecognitions
   username: root
   password: NEWPASSWORD
   host: localhost

production:
   adapter: mysql2
   database: userRecognitions
   username: root
   password: NEWPASSWORD
   host: localhost
